### ISSUE TITLE
Oura API response validation

### ISSUE THREAD

**Issue by JungeAlexander** [JungeAlexander/qself#1]
# What

Right now, `OuraAPIClient` does not validate the API response in any way which may lead to corrupt data being processed.

# Why 

Basic schema validation prior to storing the responses which will also make downstream data massaging
easier prior to data storage.
In addition, such models could be good places to document what the different fields in the API response mean.

# How

First, (manually) define pydantic models for the expected responses. They can then be used in the following ways:

1. Using a decorator (see fastapi or [this](https://medium.com/@shivamxarora/clean-and-robust-request-validations-in-python-using-pydantic-cb68d47e09c)).
2. Manual validation within the existing function calling the API.

# TODO

- [x] Implement example for workout
- [x] implement docstrings for each field as Field
- [ ] check docstrings for each field.
- [x] Define unit tests with example to see if field values and documentation work as expected

**Comment by JungeAlexander** [comment]
For example, for the [/workout](https://cloud.ouraring.com/v2/docs#tag/Workouts) endpoint this looks like:

```
{
  "data": [
    {
      "activity": "cycling",
      "calories": 300,
      "day": "2021-01-01",
      "distance": 13500.5,
      "end_datetime": "2021-01-01T01:00:00.000000+00:00",
      "intensity": "moderate",
      "label": null,
      "source": "manual",
      "start_datetime": "2021-01-01T01:30:00.000000+00:00"
    }
  ],
  "next_token": null
}
```

Sketch for a pydantic model:

```python
import datetime
from enum import Enum

from pydantic import BaseModel, Field

class OuraResponse(BaseModel):
    data: list
    next_token: str

class WorkoutIntensityEnum(str, Enum):
    easy = 'easy'
    moderate = 'moderate'
    hard = 'hard'

class OuraWorkoutData(BaseModel):
    activity: str = Field(..., description="Name of the activity")
    calories: int = Field(..., description="Active calorie burn")
    day: datetime.date = Field(..., description="Date of the activity")
    distance: float = Field(..., description="") # TODO what is this? steps?
    end_datetime: datetime.datetime = Field(..., description="End date and time")
    intensity: WorkoutIntensityEnum = Field(..., description="Workout intensity")
    label: str | None = Field(..., description="Label of the activity")  # TODO check what this looks like
    source: str = Field(..., description="Source of the activity"). # TODO check what this looks like
    start_datetime: datetime.datetime = Field(..., description="Start date and time")

class OuraWorkoutResponse(OuraResponse):
    data: list[OuraWorkoutData] # TODO add test that override works as expected
```

**Comment by JungeAlexander** [comment]
Implemented in #7
